apiVersion: v1 
kind: Pod 
metadata: 
  name: livenessexec
  labels: 
    test: liveness 
spec: 
  containers: 
  - name: liveness
    image: k8s.gcr.io/busybox
    args:
    - /server
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: custom
          value: awesome
      initialDelaySeconds: 5
      periodSeconds: 5
